apiVersion: v1
kind: ConfigMap
metadata:
  name: samba-config
data:
  smb.conf: |
    [global]
        workgroup = WORKGROUP
        server string = Samba Server

        security = user
        map to guest = Bad User
        username map = /etc/samba/username.map
        null passwords = yes

        server role = standalone server
        passdb backend = tdbsam
        load printers = no
        disable spoolss = yes

        logging = stdout
        log file = /dev/stdout
        max log size = 0
        syslog = 0

    [share]
        path = /data/samba
        writable = yes
        browseable = yes
        guest ok = yes
        force user = simadmin
        force group = simadmin
        vfs objects = full_audit
        full_audit:prefix = client=%m|auth=%U|mapped=%u|ip=%I|share=%S
        full_audit:success = connect disconnect open close read pread write pwrite mkdirat renameat unlinkat
        full_audit:failure = none
        full_audit:facility = local0
        full_audit:priority = DEBUG
        full_audit:syslog = no

  username.map: |
    simadmin = *
